// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.randioo.doudizhu_server.protocol;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CS extends
      com.google.protobuf.GeneratedMessage {
    // Use CS.newBuilder() to construct.
    private CS() {
      initFields();
    }
    private CS(boolean noInit) {}
    
    private static final CS defaultInstance;
    public static CS getDefaultInstance() {
      return defaultInstance;
    }
    
    public CS getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.ClientMessage.internal_static_com_randioo_doudizhu_server_protocol_CS_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.ClientMessage.internal_static_com_randioo_doudizhu_server_protocol_CS_fieldAccessorTable;
    }
    
    // optional .com.randioo.doudizhu_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 1;
    public static final int LOGINCHECKACCOUNTREQUEST_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountRequest;
    private com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest loginCheckAccountRequest_;
    public boolean hasLoginCheckAccountRequest() { return hasLoginCheckAccountRequest; }
    public com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() { return loginCheckAccountRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 2;
    public static final int LOGINCREATEROLEREQUEST_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleRequest;
    private com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest loginCreateRoleRequest_;
    public boolean hasLoginCreateRoleRequest() { return hasLoginCreateRoleRequest; }
    public com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() { return loginCreateRoleRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 3;
    public static final int LOGINGETROLEDATAREQUEST_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataRequest;
    private com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest loginGetRoleDataRequest_;
    public boolean hasLoginGetRoleDataRequest() { return hasLoginGetRoleDataRequest; }
    public com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() { return loginGetRoleDataRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.RoleRenameRequest RoleRenameRequest = 4;
    public static final int ROLERENAMEREQUEST_FIELD_NUMBER = 4;
    private boolean hasRoleRenameRequest;
    private com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest roleRenameRequest_;
    public boolean hasRoleRenameRequest() { return hasRoleRenameRequest; }
    public com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest getRoleRenameRequest() { return roleRenameRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.MatchCreateGameRequest MatchCreateGameRequest = 5;
    public static final int MATCHCREATEGAMEREQUEST_FIELD_NUMBER = 5;
    private boolean hasMatchCreateGameRequest;
    private com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest matchCreateGameRequest_;
    public boolean hasMatchCreateGameRequest() { return hasMatchCreateGameRequest; }
    public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest getMatchCreateGameRequest() { return matchCreateGameRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.MatchJoinGameRequest MatchJoinGameRequest = 6;
    public static final int MATCHJOINGAMEREQUEST_FIELD_NUMBER = 6;
    private boolean hasMatchJoinGameRequest;
    private com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest matchJoinGameRequest_;
    public boolean hasMatchJoinGameRequest() { return hasMatchJoinGameRequest; }
    public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest getMatchJoinGameRequest() { return matchJoinGameRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.FightReadyRequest FightReadyRequest = 7;
    public static final int FIGHTREADYREQUEST_FIELD_NUMBER = 7;
    private boolean hasFightReadyRequest;
    private com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest fightReadyRequest_;
    public boolean hasFightReadyRequest() { return hasFightReadyRequest; }
    public com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest getFightReadyRequest() { return fightReadyRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.FightExitGameRequest FightExitGameRequest = 8;
    public static final int FIGHTEXITGAMEREQUEST_FIELD_NUMBER = 8;
    private boolean hasFightExitGameRequest;
    private com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest fightExitGameRequest_;
    public boolean hasFightExitGameRequest() { return hasFightExitGameRequest; }
    public com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest getFightExitGameRequest() { return fightExitGameRequest_; }
    
    // optional .com.randioo.doudizhu_server.protocol.FightAgreeExitGameRequest FightAgreeExitGameRequest = 9;
    public static final int FIGHTAGREEEXITGAMEREQUEST_FIELD_NUMBER = 9;
    private boolean hasFightAgreeExitGameRequest;
    private com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest fightAgreeExitGameRequest_;
    public boolean hasFightAgreeExitGameRequest() { return hasFightAgreeExitGameRequest; }
    public com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest getFightAgreeExitGameRequest() { return fightAgreeExitGameRequest_; }
    
    private void initFields() {
      loginCheckAccountRequest_ = com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
      loginCreateRoleRequest_ = com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
      loginGetRoleDataRequest_ = com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      roleRenameRequest_ = com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest.getDefaultInstance();
      matchCreateGameRequest_ = com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.getDefaultInstance();
      matchJoinGameRequest_ = com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance();
      fightReadyRequest_ = com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest.getDefaultInstance();
      fightExitGameRequest_ = com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest.getDefaultInstance();
      fightAgreeExitGameRequest_ = com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountRequest()) {
        output.writeMessage(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        output.writeMessage(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        output.writeMessage(3, getLoginGetRoleDataRequest());
      }
      if (hasRoleRenameRequest()) {
        output.writeMessage(4, getRoleRenameRequest());
      }
      if (hasMatchCreateGameRequest()) {
        output.writeMessage(5, getMatchCreateGameRequest());
      }
      if (hasMatchJoinGameRequest()) {
        output.writeMessage(6, getMatchJoinGameRequest());
      }
      if (hasFightReadyRequest()) {
        output.writeMessage(7, getFightReadyRequest());
      }
      if (hasFightExitGameRequest()) {
        output.writeMessage(8, getFightExitGameRequest());
      }
      if (hasFightAgreeExitGameRequest()) {
        output.writeMessage(9, getFightAgreeExitGameRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataRequest());
      }
      if (hasRoleRenameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getRoleRenameRequest());
      }
      if (hasMatchCreateGameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMatchCreateGameRequest());
      }
      if (hasMatchJoinGameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getMatchJoinGameRequest());
      }
      if (hasFightReadyRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getFightReadyRequest());
      }
      if (hasFightExitGameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getFightExitGameRequest());
      }
      if (hasFightAgreeExitGameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getFightAgreeExitGameRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.ClientMessage.CS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.ClientMessage.CS result;
      
      // Construct using com.randioo.doudizhu_server.protocol.ClientMessage.CS.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.ClientMessage.CS();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.ClientMessage.CS internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.ClientMessage.CS();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.ClientMessage.CS.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.ClientMessage.CS getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.ClientMessage.CS.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.ClientMessage.CS build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.ClientMessage.CS buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.ClientMessage.CS buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.ClientMessage.CS returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.ClientMessage.CS) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.ClientMessage.CS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.ClientMessage.CS other) {
        if (other == com.randioo.doudizhu_server.protocol.ClientMessage.CS.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountRequest()) {
          mergeLoginCheckAccountRequest(other.getLoginCheckAccountRequest());
        }
        if (other.hasLoginCreateRoleRequest()) {
          mergeLoginCreateRoleRequest(other.getLoginCreateRoleRequest());
        }
        if (other.hasLoginGetRoleDataRequest()) {
          mergeLoginGetRoleDataRequest(other.getLoginGetRoleDataRequest());
        }
        if (other.hasRoleRenameRequest()) {
          mergeRoleRenameRequest(other.getRoleRenameRequest());
        }
        if (other.hasMatchCreateGameRequest()) {
          mergeMatchCreateGameRequest(other.getMatchCreateGameRequest());
        }
        if (other.hasMatchJoinGameRequest()) {
          mergeMatchJoinGameRequest(other.getMatchJoinGameRequest());
        }
        if (other.hasFightReadyRequest()) {
          mergeFightReadyRequest(other.getFightReadyRequest());
        }
        if (other.hasFightExitGameRequest()) {
          mergeFightExitGameRequest(other.getFightExitGameRequest());
        }
        if (other.hasFightAgreeExitGameRequest()) {
          mergeFightAgreeExitGameRequest(other.getFightAgreeExitGameRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest.newBuilder();
              if (hasLoginCheckAccountRequest()) {
                subBuilder.mergeFrom(getLoginCheckAccountRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest.newBuilder();
              if (hasLoginCreateRoleRequest()) {
                subBuilder.mergeFrom(getLoginCreateRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest.newBuilder();
              if (hasLoginGetRoleDataRequest()) {
                subBuilder.mergeFrom(getLoginGetRoleDataRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest.newBuilder();
              if (hasRoleRenameRequest()) {
                subBuilder.mergeFrom(getRoleRenameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRoleRenameRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.newBuilder();
              if (hasMatchCreateGameRequest()) {
                subBuilder.mergeFrom(getMatchCreateGameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchCreateGameRequest(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.newBuilder();
              if (hasMatchJoinGameRequest()) {
                subBuilder.mergeFrom(getMatchJoinGameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchJoinGameRequest(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest.newBuilder();
              if (hasFightReadyRequest()) {
                subBuilder.mergeFrom(getFightReadyRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightReadyRequest(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest.newBuilder();
              if (hasFightExitGameRequest()) {
                subBuilder.mergeFrom(getFightExitGameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightExitGameRequest(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest.Builder subBuilder = com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest.newBuilder();
              if (hasFightAgreeExitGameRequest()) {
                subBuilder.mergeFrom(getFightAgreeExitGameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightAgreeExitGameRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.doudizhu_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 1;
      public boolean hasLoginCheckAccountRequest() {
        return result.hasLoginCheckAccountRequest();
      }
      public com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() {
        return result.getLoginCheckAccountRequest();
      }
      public Builder setLoginCheckAccountRequest(com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = value;
        return this;
      }
      public Builder setLoginCheckAccountRequest(com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest.Builder builderForValue) {
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountRequest(com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest value) {
        if (result.hasLoginCheckAccountRequest() &&
            result.loginCheckAccountRequest_ != com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance()) {
          result.loginCheckAccountRequest_ =
            com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest.newBuilder(result.loginCheckAccountRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountRequest_ = value;
        }
        result.hasLoginCheckAccountRequest = true;
        return this;
      }
      public Builder clearLoginCheckAccountRequest() {
        result.hasLoginCheckAccountRequest = false;
        result.loginCheckAccountRequest_ = com.randioo.doudizhu_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 2;
      public boolean hasLoginCreateRoleRequest() {
        return result.hasLoginCreateRoleRequest();
      }
      public com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() {
        return result.getLoginCreateRoleRequest();
      }
      public Builder setLoginCreateRoleRequest(com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = value;
        return this;
      }
      public Builder setLoginCreateRoleRequest(com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest.Builder builderForValue) {
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleRequest(com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest value) {
        if (result.hasLoginCreateRoleRequest() &&
            result.loginCreateRoleRequest_ != com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance()) {
          result.loginCreateRoleRequest_ =
            com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest.newBuilder(result.loginCreateRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleRequest_ = value;
        }
        result.hasLoginCreateRoleRequest = true;
        return this;
      }
      public Builder clearLoginCreateRoleRequest() {
        result.hasLoginCreateRoleRequest = false;
        result.loginCreateRoleRequest_ = com.randioo.doudizhu_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 3;
      public boolean hasLoginGetRoleDataRequest() {
        return result.hasLoginGetRoleDataRequest();
      }
      public com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() {
        return result.getLoginGetRoleDataRequest();
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest.Builder builderForValue) {
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataRequest(com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (result.hasLoginGetRoleDataRequest() &&
            result.loginGetRoleDataRequest_ != com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) {
          result.loginGetRoleDataRequest_ =
            com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest.newBuilder(result.loginGetRoleDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataRequest_ = value;
        }
        result.hasLoginGetRoleDataRequest = true;
        return this;
      }
      public Builder clearLoginGetRoleDataRequest() {
        result.hasLoginGetRoleDataRequest = false;
        result.loginGetRoleDataRequest_ = com.randioo.doudizhu_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.RoleRenameRequest RoleRenameRequest = 4;
      public boolean hasRoleRenameRequest() {
        return result.hasRoleRenameRequest();
      }
      public com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest getRoleRenameRequest() {
        return result.getRoleRenameRequest();
      }
      public Builder setRoleRenameRequest(com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRoleRenameRequest = true;
        result.roleRenameRequest_ = value;
        return this;
      }
      public Builder setRoleRenameRequest(com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest.Builder builderForValue) {
        result.hasRoleRenameRequest = true;
        result.roleRenameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeRoleRenameRequest(com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest value) {
        if (result.hasRoleRenameRequest() &&
            result.roleRenameRequest_ != com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest.getDefaultInstance()) {
          result.roleRenameRequest_ =
            com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest.newBuilder(result.roleRenameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.roleRenameRequest_ = value;
        }
        result.hasRoleRenameRequest = true;
        return this;
      }
      public Builder clearRoleRenameRequest() {
        result.hasRoleRenameRequest = false;
        result.roleRenameRequest_ = com.randioo.doudizhu_server.protocol.Role.RoleRenameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.MatchCreateGameRequest MatchCreateGameRequest = 5;
      public boolean hasMatchCreateGameRequest() {
        return result.hasMatchCreateGameRequest();
      }
      public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest getMatchCreateGameRequest() {
        return result.getMatchCreateGameRequest();
      }
      public Builder setMatchCreateGameRequest(com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchCreateGameRequest = true;
        result.matchCreateGameRequest_ = value;
        return this;
      }
      public Builder setMatchCreateGameRequest(com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.Builder builderForValue) {
        result.hasMatchCreateGameRequest = true;
        result.matchCreateGameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchCreateGameRequest(com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest value) {
        if (result.hasMatchCreateGameRequest() &&
            result.matchCreateGameRequest_ != com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.getDefaultInstance()) {
          result.matchCreateGameRequest_ =
            com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.newBuilder(result.matchCreateGameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.matchCreateGameRequest_ = value;
        }
        result.hasMatchCreateGameRequest = true;
        return this;
      }
      public Builder clearMatchCreateGameRequest() {
        result.hasMatchCreateGameRequest = false;
        result.matchCreateGameRequest_ = com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.MatchJoinGameRequest MatchJoinGameRequest = 6;
      public boolean hasMatchJoinGameRequest() {
        return result.hasMatchJoinGameRequest();
      }
      public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest getMatchJoinGameRequest() {
        return result.getMatchJoinGameRequest();
      }
      public Builder setMatchJoinGameRequest(com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchJoinGameRequest = true;
        result.matchJoinGameRequest_ = value;
        return this;
      }
      public Builder setMatchJoinGameRequest(com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.Builder builderForValue) {
        result.hasMatchJoinGameRequest = true;
        result.matchJoinGameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchJoinGameRequest(com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest value) {
        if (result.hasMatchJoinGameRequest() &&
            result.matchJoinGameRequest_ != com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance()) {
          result.matchJoinGameRequest_ =
            com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.newBuilder(result.matchJoinGameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.matchJoinGameRequest_ = value;
        }
        result.hasMatchJoinGameRequest = true;
        return this;
      }
      public Builder clearMatchJoinGameRequest() {
        result.hasMatchJoinGameRequest = false;
        result.matchJoinGameRequest_ = com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.FightReadyRequest FightReadyRequest = 7;
      public boolean hasFightReadyRequest() {
        return result.hasFightReadyRequest();
      }
      public com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest getFightReadyRequest() {
        return result.getFightReadyRequest();
      }
      public Builder setFightReadyRequest(com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightReadyRequest = true;
        result.fightReadyRequest_ = value;
        return this;
      }
      public Builder setFightReadyRequest(com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest.Builder builderForValue) {
        result.hasFightReadyRequest = true;
        result.fightReadyRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightReadyRequest(com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest value) {
        if (result.hasFightReadyRequest() &&
            result.fightReadyRequest_ != com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest.getDefaultInstance()) {
          result.fightReadyRequest_ =
            com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest.newBuilder(result.fightReadyRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightReadyRequest_ = value;
        }
        result.hasFightReadyRequest = true;
        return this;
      }
      public Builder clearFightReadyRequest() {
        result.hasFightReadyRequest = false;
        result.fightReadyRequest_ = com.randioo.doudizhu_server.protocol.Fight.FightReadyRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.FightExitGameRequest FightExitGameRequest = 8;
      public boolean hasFightExitGameRequest() {
        return result.hasFightExitGameRequest();
      }
      public com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest getFightExitGameRequest() {
        return result.getFightExitGameRequest();
      }
      public Builder setFightExitGameRequest(com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightExitGameRequest = true;
        result.fightExitGameRequest_ = value;
        return this;
      }
      public Builder setFightExitGameRequest(com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest.Builder builderForValue) {
        result.hasFightExitGameRequest = true;
        result.fightExitGameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightExitGameRequest(com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest value) {
        if (result.hasFightExitGameRequest() &&
            result.fightExitGameRequest_ != com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest.getDefaultInstance()) {
          result.fightExitGameRequest_ =
            com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest.newBuilder(result.fightExitGameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightExitGameRequest_ = value;
        }
        result.hasFightExitGameRequest = true;
        return this;
      }
      public Builder clearFightExitGameRequest() {
        result.hasFightExitGameRequest = false;
        result.fightExitGameRequest_ = com.randioo.doudizhu_server.protocol.Fight.FightExitGameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.FightAgreeExitGameRequest FightAgreeExitGameRequest = 9;
      public boolean hasFightAgreeExitGameRequest() {
        return result.hasFightAgreeExitGameRequest();
      }
      public com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest getFightAgreeExitGameRequest() {
        return result.getFightAgreeExitGameRequest();
      }
      public Builder setFightAgreeExitGameRequest(com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightAgreeExitGameRequest = true;
        result.fightAgreeExitGameRequest_ = value;
        return this;
      }
      public Builder setFightAgreeExitGameRequest(com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest.Builder builderForValue) {
        result.hasFightAgreeExitGameRequest = true;
        result.fightAgreeExitGameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightAgreeExitGameRequest(com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest value) {
        if (result.hasFightAgreeExitGameRequest() &&
            result.fightAgreeExitGameRequest_ != com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest.getDefaultInstance()) {
          result.fightAgreeExitGameRequest_ =
            com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest.newBuilder(result.fightAgreeExitGameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightAgreeExitGameRequest_ = value;
        }
        result.hasFightAgreeExitGameRequest = true;
        return this;
      }
      public Builder clearFightAgreeExitGameRequest() {
        result.hasFightAgreeExitGameRequest = false;
        result.fightAgreeExitGameRequest_ = com.randioo.doudizhu_server.protocol.Fight.FightAgreeExitGameRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.CS)
    }
    
    static {
      defaultInstance = new CS(true);
      com.randioo.doudizhu_server.protocol.ClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.CS)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_CS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_CS_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\022$com.randioo.doudi" +
      "zhu_server.protocol\032\013Login.proto\032\nRole.p" +
      "roto\032\013Match.proto\032\013Fight.proto\"\302\006\n\002CS\022`\n" +
      "\030LoginCheckAccountRequest\030\001 \001(\0132>.com.ra" +
      "ndioo.doudizhu_server.protocol.LoginChec" +
      "kAccountRequest\022\\\n\026LoginCreateRoleReques" +
      "t\030\002 \001(\0132<.com.randioo.doudizhu_server.pr" +
      "otocol.LoginCreateRoleRequest\022^\n\027LoginGe" +
      "tRoleDataRequest\030\003 \001(\0132=.com.randioo.dou" +
      "dizhu_server.protocol.LoginGetRoleDataRe",
      "quest\022R\n\021RoleRenameRequest\030\004 \001(\01327.com.r" +
      "andioo.doudizhu_server.protocol.RoleRena" +
      "meRequest\022\\\n\026MatchCreateGameRequest\030\005 \001(" +
      "\0132<.com.randioo.doudizhu_server.protocol" +
      ".MatchCreateGameRequest\022X\n\024MatchJoinGame" +
      "Request\030\006 \001(\0132:.com.randioo.doudizhu_ser" +
      "ver.protocol.MatchJoinGameRequest\022R\n\021Fig" +
      "htReadyRequest\030\007 \001(\01327.com.randioo.doudi" +
      "zhu_server.protocol.FightReadyRequest\022X\n" +
      "\024FightExitGameRequest\030\010 \001(\0132:.com.randio",
      "o.doudizhu_server.protocol.FightExitGame" +
      "Request\022b\n\031FightAgreeExitGameRequest\030\t \001" +
      "(\0132?.com.randioo.doudizhu_server.protoco" +
      "l.FightAgreeExitGameRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_doudizhu_server_protocol_CS_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_doudizhu_server_protocol_CS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_CS_descriptor,
              new java.lang.String[] { "LoginCheckAccountRequest", "LoginCreateRoleRequest", "LoginGetRoleDataRequest", "RoleRenameRequest", "MatchCreateGameRequest", "MatchJoinGameRequest", "FightReadyRequest", "FightExitGameRequest", "FightAgreeExitGameRequest", },
              com.randioo.doudizhu_server.protocol.ClientMessage.CS.class,
              com.randioo.doudizhu_server.protocol.ClientMessage.CS.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.doudizhu_server.protocol.Login.getDescriptor(),
          com.randioo.doudizhu_server.protocol.Role.getDescriptor(),
          com.randioo.doudizhu_server.protocol.Match.getDescriptor(),
          com.randioo.doudizhu_server.protocol.Fight.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
