// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Entity.proto

package com.randioo.doudizhu_server.protocol;

public final class Entity {
  private Entity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum GameType
      implements com.google.protobuf.ProtocolMessageEnum {
    GAME_TYPE_MATCH(0, 1),
    GAME_TYPE_FRIEND(1, 2),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static GameType valueOf(int value) {
      switch (value) {
        case 1: return GAME_TYPE_MATCH;
        case 2: return GAME_TYPE_FRIEND;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameType>() {
            public GameType findValueByNumber(int number) {
              return GameType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Entity.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final GameType[] VALUES = {
      GAME_TYPE_MATCH, GAME_TYPE_FRIEND, 
    };
    public static GameType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private GameType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.randioo.doudizhu_server.protocol.Entity.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:com.randioo.doudizhu_server.protocol.GameType)
  }
  
  public enum GameState
      implements com.google.protobuf.ProtocolMessageEnum {
    GAME_STATE_PREPARE(0, 1),
    GAME_START_START(1, 2),
    GAME_START_END(2, 3),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static GameState valueOf(int value) {
      switch (value) {
        case 1: return GAME_STATE_PREPARE;
        case 2: return GAME_START_START;
        case 3: return GAME_START_END;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameState>() {
            public GameState findValueByNumber(int number) {
              return GameState.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Entity.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final GameState[] VALUES = {
      GAME_STATE_PREPARE, GAME_START_START, GAME_START_END, 
    };
    public static GameState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private GameState(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.randioo.doudizhu_server.protocol.Entity.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:com.randioo.doudizhu_server.protocol.GameState)
  }
  
  public static final class RoleData extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleData.newBuilder() to construct.
    private RoleData() {
      initFields();
    }
    private RoleData(boolean noInit) {}
    
    private static final RoleData defaultInstance;
    public static RoleData getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Entity.internal_static_com_randioo_doudizhu_server_protocol_RoleData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Entity.internal_static_com_randioo_doudizhu_server_protocol_RoleData_fieldAccessorTable;
    }
    
    // optional int32 roleId = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private boolean hasRoleId;
    private int roleId_ = 0;
    public boolean hasRoleId() { return hasRoleId; }
    public int getRoleId() { return roleId_; }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int32 money = 3;
    public static final int MONEY_FIELD_NUMBER = 3;
    private boolean hasMoney;
    private int money_ = 0;
    public boolean hasMoney() { return hasMoney; }
    public int getMoney() { return money_; }
    
    // optional int32 volume = 4;
    public static final int VOLUME_FIELD_NUMBER = 4;
    private boolean hasVolume;
    private int volume_ = 0;
    public boolean hasVolume() { return hasVolume; }
    public int getVolume() { return volume_; }
    
    // optional int32 musicVolume = 5;
    public static final int MUSICVOLUME_FIELD_NUMBER = 5;
    private boolean hasMusicVolume;
    private int musicVolume_ = 0;
    public boolean hasMusicVolume() { return hasMusicVolume; }
    public int getMusicVolume() { return musicVolume_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRoleId()) {
        output.writeInt32(1, getRoleId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasMoney()) {
        output.writeInt32(3, getMoney());
      }
      if (hasVolume()) {
        output.writeInt32(4, getVolume());
      }
      if (hasMusicVolume()) {
        output.writeInt32(5, getMusicVolume());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRoleId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getRoleId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getMoney());
      }
      if (hasVolume()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getVolume());
      }
      if (hasMusicVolume()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getMusicVolume());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Entity.RoleData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Entity.RoleData result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Entity.RoleData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Entity.RoleData();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Entity.RoleData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Entity.RoleData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Entity.RoleData.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Entity.RoleData getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Entity.RoleData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Entity.RoleData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Entity.RoleData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Entity.RoleData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Entity.RoleData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Entity.RoleData) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Entity.RoleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Entity.RoleData other) {
        if (other == com.randioo.doudizhu_server.protocol.Entity.RoleData.getDefaultInstance()) return this;
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasMusicVolume()) {
          setMusicVolume(other.getMusicVolume());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRoleId(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 24: {
              setMoney(input.readInt32());
              break;
            }
            case 32: {
              setVolume(input.readInt32());
              break;
            }
            case 40: {
              setMusicVolume(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 roleId = 1;
      public boolean hasRoleId() {
        return result.hasRoleId();
      }
      public int getRoleId() {
        return result.getRoleId();
      }
      public Builder setRoleId(int value) {
        result.hasRoleId = true;
        result.roleId_ = value;
        return this;
      }
      public Builder clearRoleId() {
        result.hasRoleId = false;
        result.roleId_ = 0;
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional int32 money = 3;
      public boolean hasMoney() {
        return result.hasMoney();
      }
      public int getMoney() {
        return result.getMoney();
      }
      public Builder setMoney(int value) {
        result.hasMoney = true;
        result.money_ = value;
        return this;
      }
      public Builder clearMoney() {
        result.hasMoney = false;
        result.money_ = 0;
        return this;
      }
      
      // optional int32 volume = 4;
      public boolean hasVolume() {
        return result.hasVolume();
      }
      public int getVolume() {
        return result.getVolume();
      }
      public Builder setVolume(int value) {
        result.hasVolume = true;
        result.volume_ = value;
        return this;
      }
      public Builder clearVolume() {
        result.hasVolume = false;
        result.volume_ = 0;
        return this;
      }
      
      // optional int32 musicVolume = 5;
      public boolean hasMusicVolume() {
        return result.hasMusicVolume();
      }
      public int getMusicVolume() {
        return result.getMusicVolume();
      }
      public Builder setMusicVolume(int value) {
        result.hasMusicVolume = true;
        result.musicVolume_ = value;
        return this;
      }
      public Builder clearMusicVolume() {
        result.hasMusicVolume = false;
        result.musicVolume_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.RoleData)
    }
    
    static {
      defaultInstance = new RoleData(true);
      com.randioo.doudizhu_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.RoleData)
  }
  
  public static final class GameConfig extends
      com.google.protobuf.GeneratedMessage {
    // Use GameConfig.newBuilder() to construct.
    private GameConfig() {
      initFields();
    }
    private GameConfig(boolean noInit) {}
    
    private static final GameConfig defaultInstance;
    public static GameConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Entity.internal_static_com_randioo_doudizhu_server_protocol_GameConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Entity.internal_static_com_randioo_doudizhu_server_protocol_GameConfig_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Entity.GameConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Entity.GameConfig result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Entity.GameConfig.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Entity.GameConfig();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Entity.GameConfig internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Entity.GameConfig();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Entity.GameConfig.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Entity.GameConfig getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Entity.GameConfig.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Entity.GameConfig build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Entity.GameConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Entity.GameConfig buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Entity.GameConfig returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Entity.GameConfig) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Entity.GameConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Entity.GameConfig other) {
        if (other == com.randioo.doudizhu_server.protocol.Entity.GameConfig.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.GameConfig)
    }
    
    static {
      defaultInstance = new GameConfig(true);
      com.randioo.doudizhu_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.GameConfig)
  }
  
  public static final class GameRoleData extends
      com.google.protobuf.GeneratedMessage {
    // Use GameRoleData.newBuilder() to construct.
    private GameRoleData() {
      initFields();
    }
    private GameRoleData(boolean noInit) {}
    
    private static final GameRoleData defaultInstance;
    public static GameRoleData getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameRoleData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Entity.internal_static_com_randioo_doudizhu_server_protocol_GameRoleData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Entity.internal_static_com_randioo_doudizhu_server_protocol_GameRoleData_fieldAccessorTable;
    }
    
    // optional string gameRoleId = 1;
    public static final int GAMEROLEID_FIELD_NUMBER = 1;
    private boolean hasGameRoleId;
    private java.lang.String gameRoleId_ = "";
    public boolean hasGameRoleId() { return hasGameRoleId; }
    public java.lang.String getGameRoleId() { return gameRoleId_; }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int32 seated = 3;
    public static final int SEATED_FIELD_NUMBER = 3;
    private boolean hasSeated;
    private int seated_ = 0;
    public boolean hasSeated() { return hasSeated; }
    public int getSeated() { return seated_; }
    
    // optional bool ready = 4;
    public static final int READY_FIELD_NUMBER = 4;
    private boolean hasReady;
    private boolean ready_ = false;
    public boolean hasReady() { return hasReady; }
    public boolean getReady() { return ready_; }
    
    // optional int32 seatIndex = 5;
    public static final int SEATINDEX_FIELD_NUMBER = 5;
    private boolean hasSeatIndex;
    private int seatIndex_ = 0;
    public boolean hasSeatIndex() { return hasSeatIndex; }
    public int getSeatIndex() { return seatIndex_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGameRoleId()) {
        output.writeString(1, getGameRoleId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasSeated()) {
        output.writeInt32(3, getSeated());
      }
      if (hasReady()) {
        output.writeBool(4, getReady());
      }
      if (hasSeatIndex()) {
        output.writeInt32(5, getSeatIndex());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameRoleId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getGameRoleId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasSeated()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getSeated());
      }
      if (hasReady()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, getReady());
      }
      if (hasSeatIndex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getSeatIndex());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Entity.GameRoleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Entity.GameRoleData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Entity.GameRoleData result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Entity.GameRoleData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Entity.GameRoleData();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Entity.GameRoleData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Entity.GameRoleData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Entity.GameRoleData getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Entity.GameRoleData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Entity.GameRoleData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Entity.GameRoleData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Entity.GameRoleData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Entity.GameRoleData) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Entity.GameRoleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Entity.GameRoleData other) {
        if (other == com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance()) return this;
        if (other.hasGameRoleId()) {
          setGameRoleId(other.getGameRoleId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasSeated()) {
          setSeated(other.getSeated());
        }
        if (other.hasReady()) {
          setReady(other.getReady());
        }
        if (other.hasSeatIndex()) {
          setSeatIndex(other.getSeatIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setGameRoleId(input.readString());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 24: {
              setSeated(input.readInt32());
              break;
            }
            case 32: {
              setReady(input.readBool());
              break;
            }
            case 40: {
              setSeatIndex(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string gameRoleId = 1;
      public boolean hasGameRoleId() {
        return result.hasGameRoleId();
      }
      public java.lang.String getGameRoleId() {
        return result.getGameRoleId();
      }
      public Builder setGameRoleId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGameRoleId = true;
        result.gameRoleId_ = value;
        return this;
      }
      public Builder clearGameRoleId() {
        result.hasGameRoleId = false;
        result.gameRoleId_ = getDefaultInstance().getGameRoleId();
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional int32 seated = 3;
      public boolean hasSeated() {
        return result.hasSeated();
      }
      public int getSeated() {
        return result.getSeated();
      }
      public Builder setSeated(int value) {
        result.hasSeated = true;
        result.seated_ = value;
        return this;
      }
      public Builder clearSeated() {
        result.hasSeated = false;
        result.seated_ = 0;
        return this;
      }
      
      // optional bool ready = 4;
      public boolean hasReady() {
        return result.hasReady();
      }
      public boolean getReady() {
        return result.getReady();
      }
      public Builder setReady(boolean value) {
        result.hasReady = true;
        result.ready_ = value;
        return this;
      }
      public Builder clearReady() {
        result.hasReady = false;
        result.ready_ = false;
        return this;
      }
      
      // optional int32 seatIndex = 5;
      public boolean hasSeatIndex() {
        return result.hasSeatIndex();
      }
      public int getSeatIndex() {
        return result.getSeatIndex();
      }
      public Builder setSeatIndex(int value) {
        result.hasSeatIndex = true;
        result.seatIndex_ = value;
        return this;
      }
      public Builder clearSeatIndex() {
        result.hasSeatIndex = false;
        result.seatIndex_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.GameRoleData)
    }
    
    static {
      defaultInstance = new GameRoleData(true);
      com.randioo.doudizhu_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.GameRoleData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_RoleData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_RoleData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_GameConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_GameConfig_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_GameRoleData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_GameRoleData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Entity.proto\022$com.randioo.doudizhu_ser" +
      "ver.protocol\"\\\n\010RoleData\022\016\n\006roleId\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\r\n\005money\030\003 \001(\005\022\016\n\006volume\030" +
      "\004 \001(\005\022\023\n\013musicVolume\030\005 \001(\005\"\014\n\nGameConfig" +
      "\"b\n\014GameRoleData\022\022\n\ngameRoleId\030\001 \001(\t\022\014\n\004" +
      "name\030\002 \001(\t\022\016\n\006seated\030\003 \001(\005\022\r\n\005ready\030\004 \001(" +
      "\010\022\021\n\tseatIndex\030\005 \001(\005*5\n\010GameType\022\023\n\017GAME" +
      "_TYPE_MATCH\020\001\022\024\n\020GAME_TYPE_FRIEND\020\002*M\n\tG" +
      "ameState\022\026\n\022GAME_STATE_PREPARE\020\001\022\024\n\020GAME" +
      "_START_START\020\002\022\022\n\016GAME_START_END\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_doudizhu_server_protocol_RoleData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_doudizhu_server_protocol_RoleData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_RoleData_descriptor,
              new java.lang.String[] { "RoleId", "Name", "Money", "Volume", "MusicVolume", },
              com.randioo.doudizhu_server.protocol.Entity.RoleData.class,
              com.randioo.doudizhu_server.protocol.Entity.RoleData.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_GameConfig_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_doudizhu_server_protocol_GameConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_GameConfig_descriptor,
              new java.lang.String[] { },
              com.randioo.doudizhu_server.protocol.Entity.GameConfig.class,
              com.randioo.doudizhu_server.protocol.Entity.GameConfig.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_GameRoleData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_doudizhu_server_protocol_GameRoleData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_GameRoleData_descriptor,
              new java.lang.String[] { "GameRoleId", "Name", "Seated", "Ready", "SeatIndex", },
              com.randioo.doudizhu_server.protocol.Entity.GameRoleData.class,
              com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
