// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Match.proto

package com.randioo.doudizhu_server.protocol;

public final class Match {
  private Match() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class MatchCreateGameRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MatchCreateGameRequest.newBuilder() to construct.
    private MatchCreateGameRequest() {
      initFields();
    }
    private MatchCreateGameRequest(boolean noInit) {}
    
    private static final MatchCreateGameRequest defaultInstance;
    public static MatchCreateGameRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MatchCreateGameRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameRequest_fieldAccessorTable;
    }
    
    // optional .com.randioo.doudizhu_server.protocol.GameConfig gameConfig = 1;
    public static final int GAMECONFIG_FIELD_NUMBER = 1;
    private boolean hasGameConfig;
    private com.randioo.doudizhu_server.protocol.Entity.GameConfig gameConfig_;
    public boolean hasGameConfig() { return hasGameConfig; }
    public com.randioo.doudizhu_server.protocol.Entity.GameConfig getGameConfig() { return gameConfig_; }
    
    private void initFields() {
      gameConfig_ = com.randioo.doudizhu_server.protocol.Entity.GameConfig.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGameConfig()) {
        output.writeMessage(1, getGameConfig());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameConfig()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGameConfig());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.getDefaultInstance()) return this;
        if (other.hasGameConfig()) {
          mergeGameConfig(other.getGameConfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.doudizhu_server.protocol.Entity.GameConfig.Builder subBuilder = com.randioo.doudizhu_server.protocol.Entity.GameConfig.newBuilder();
              if (hasGameConfig()) {
                subBuilder.mergeFrom(getGameConfig());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGameConfig(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.doudizhu_server.protocol.GameConfig gameConfig = 1;
      public boolean hasGameConfig() {
        return result.hasGameConfig();
      }
      public com.randioo.doudizhu_server.protocol.Entity.GameConfig getGameConfig() {
        return result.getGameConfig();
      }
      public Builder setGameConfig(com.randioo.doudizhu_server.protocol.Entity.GameConfig value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameConfig = true;
        result.gameConfig_ = value;
        return this;
      }
      public Builder setGameConfig(com.randioo.doudizhu_server.protocol.Entity.GameConfig.Builder builderForValue) {
        result.hasGameConfig = true;
        result.gameConfig_ = builderForValue.build();
        return this;
      }
      public Builder mergeGameConfig(com.randioo.doudizhu_server.protocol.Entity.GameConfig value) {
        if (result.hasGameConfig() &&
            result.gameConfig_ != com.randioo.doudizhu_server.protocol.Entity.GameConfig.getDefaultInstance()) {
          result.gameConfig_ =
            com.randioo.doudizhu_server.protocol.Entity.GameConfig.newBuilder(result.gameConfig_).mergeFrom(value).buildPartial();
        } else {
          result.gameConfig_ = value;
        }
        result.hasGameConfig = true;
        return this;
      }
      public Builder clearGameConfig() {
        result.hasGameConfig = false;
        result.gameConfig_ = com.randioo.doudizhu_server.protocol.Entity.GameConfig.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.MatchCreateGameRequest)
    }
    
    static {
      defaultInstance = new MatchCreateGameRequest(true);
      com.randioo.doudizhu_server.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.MatchCreateGameRequest)
  }
  
  public static final class MatchAIRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MatchAIRequest.newBuilder() to construct.
    private MatchAIRequest() {
      initFields();
    }
    private MatchAIRequest(boolean noInit) {}
    
    private static final MatchAIRequest defaultInstance;
    public static MatchAIRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MatchAIRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchAIRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchAIRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchAIRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Match.MatchAIRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Match.MatchAIRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Match.MatchAIRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Match.MatchAIRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Match.MatchAIRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Match.MatchAIRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchAIRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchAIRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchAIRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Match.MatchAIRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Match.MatchAIRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchAIRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Match.MatchAIRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Match.MatchAIRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Match.MatchAIRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Match.MatchAIRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Match.MatchAIRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.MatchAIRequest)
    }
    
    static {
      defaultInstance = new MatchAIRequest(true);
      com.randioo.doudizhu_server.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.MatchAIRequest)
  }
  
  public static final class MatchCreateGameResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MatchCreateGameResponse.newBuilder() to construct.
    private MatchCreateGameResponse() {
      initFields();
    }
    private MatchCreateGameResponse(boolean noInit) {}
    
    private static final MatchCreateGameResponse defaultInstance;
    public static MatchCreateGameResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MatchCreateGameResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional string id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private boolean hasId;
    private java.lang.String id_ = "";
    public boolean hasId() { return hasId; }
    public java.lang.String getId() { return id_; }
    
    // optional bool moguai = 3;
    public static final int MOGUAI_FIELD_NUMBER = 3;
    private boolean hasMoguai;
    private boolean moguai_ = false;
    public boolean hasMoguai() { return hasMoguai; }
    public boolean getMoguai() { return moguai_; }
    
    // optional .com.randioo.doudizhu_server.protocol.GameRoleData gameRoleData = 4;
    public static final int GAMEROLEDATA_FIELD_NUMBER = 4;
    private boolean hasGameRoleData;
    private com.randioo.doudizhu_server.protocol.Entity.GameRoleData gameRoleData_;
    public boolean hasGameRoleData() { return hasGameRoleData; }
    public com.randioo.doudizhu_server.protocol.Entity.GameRoleData getGameRoleData() { return gameRoleData_; }
    
    private void initFields() {
      gameRoleData_ = com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasId()) {
        output.writeString(2, getId());
      }
      if (hasMoguai()) {
        output.writeBool(3, getMoguai());
      }
      if (hasGameRoleData()) {
        output.writeMessage(4, getGameRoleData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getId());
      }
      if (hasMoguai()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getMoguai());
      }
      if (hasGameRoleData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGameRoleData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse other) {
        if (other == com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMoguai()) {
          setMoguai(other.getMoguai());
        }
        if (other.hasGameRoleData()) {
          mergeGameRoleData(other.getGameRoleData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              setId(input.readString());
              break;
            }
            case 24: {
              setMoguai(input.readBool());
              break;
            }
            case 34: {
              com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder subBuilder = com.randioo.doudizhu_server.protocol.Entity.GameRoleData.newBuilder();
              if (hasGameRoleData()) {
                subBuilder.mergeFrom(getGameRoleData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGameRoleData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional string id = 2;
      public boolean hasId() {
        return result.hasId();
      }
      public java.lang.String getId() {
        return result.getId();
      }
      public Builder setId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = getDefaultInstance().getId();
        return this;
      }
      
      // optional bool moguai = 3;
      public boolean hasMoguai() {
        return result.hasMoguai();
      }
      public boolean getMoguai() {
        return result.getMoguai();
      }
      public Builder setMoguai(boolean value) {
        result.hasMoguai = true;
        result.moguai_ = value;
        return this;
      }
      public Builder clearMoguai() {
        result.hasMoguai = false;
        result.moguai_ = false;
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.GameRoleData gameRoleData = 4;
      public boolean hasGameRoleData() {
        return result.hasGameRoleData();
      }
      public com.randioo.doudizhu_server.protocol.Entity.GameRoleData getGameRoleData() {
        return result.getGameRoleData();
      }
      public Builder setGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameRoleData = true;
        result.gameRoleData_ = value;
        return this;
      }
      public Builder setGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder builderForValue) {
        result.hasGameRoleData = true;
        result.gameRoleData_ = builderForValue.build();
        return this;
      }
      public Builder mergeGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData value) {
        if (result.hasGameRoleData() &&
            result.gameRoleData_ != com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance()) {
          result.gameRoleData_ =
            com.randioo.doudizhu_server.protocol.Entity.GameRoleData.newBuilder(result.gameRoleData_).mergeFrom(value).buildPartial();
        } else {
          result.gameRoleData_ = value;
        }
        result.hasGameRoleData = true;
        return this;
      }
      public Builder clearGameRoleData() {
        result.hasGameRoleData = false;
        result.gameRoleData_ = com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.MatchCreateGameResponse)
    }
    
    static {
      defaultInstance = new MatchCreateGameResponse(true);
      com.randioo.doudizhu_server.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.MatchCreateGameResponse)
  }
  
  public static final class MatchJoinGameRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MatchJoinGameRequest.newBuilder() to construct.
    private MatchJoinGameRequest() {
      initFields();
    }
    private MatchJoinGameRequest(boolean noInit) {}
    
    private static final MatchJoinGameRequest defaultInstance;
    public static MatchJoinGameRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MatchJoinGameRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameRequest_fieldAccessorTable;
    }
    
    // optional string lockString = 1;
    public static final int LOCKSTRING_FIELD_NUMBER = 1;
    private boolean hasLockString;
    private java.lang.String lockString_ = "";
    public boolean hasLockString() { return hasLockString; }
    public java.lang.String getLockString() { return lockString_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLockString()) {
        output.writeString(1, getLockString());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLockString()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getLockString());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance()) return this;
        if (other.hasLockString()) {
          setLockString(other.getLockString());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setLockString(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string lockString = 1;
      public boolean hasLockString() {
        return result.hasLockString();
      }
      public java.lang.String getLockString() {
        return result.getLockString();
      }
      public Builder setLockString(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLockString = true;
        result.lockString_ = value;
        return this;
      }
      public Builder clearLockString() {
        result.hasLockString = false;
        result.lockString_ = getDefaultInstance().getLockString();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.MatchJoinGameRequest)
    }
    
    static {
      defaultInstance = new MatchJoinGameRequest(true);
      com.randioo.doudizhu_server.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.MatchJoinGameRequest)
  }
  
  public static final class MatchJoinGameResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MatchJoinGameResponse.newBuilder() to construct.
    private MatchJoinGameResponse() {
      initFields();
    }
    private MatchJoinGameResponse(boolean noInit) {}
    
    private static final MatchJoinGameResponse defaultInstance;
    public static MatchJoinGameResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MatchJoinGameResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // repeated .com.randioo.doudizhu_server.protocol.GameRoleData gameRoleData = 2;
    public static final int GAMEROLEDATA_FIELD_NUMBER = 2;
    private java.util.List<com.randioo.doudizhu_server.protocol.Entity.GameRoleData> gameRoleData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.doudizhu_server.protocol.Entity.GameRoleData> getGameRoleDataList() {
      return gameRoleData_;
    }
    public int getGameRoleDataCount() { return gameRoleData_.size(); }
    public com.randioo.doudizhu_server.protocol.Entity.GameRoleData getGameRoleData(int index) {
      return gameRoleData_.get(index);
    }
    
    // optional string id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private boolean hasId;
    private java.lang.String id_ = "";
    public boolean hasId() { return hasId; }
    public java.lang.String getId() { return id_; }
    
    // optional bool moguai = 4;
    public static final int MOGUAI_FIELD_NUMBER = 4;
    private boolean hasMoguai;
    private boolean moguai_ = false;
    public boolean hasMoguai() { return hasMoguai; }
    public boolean getMoguai() { return moguai_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      for (com.randioo.doudizhu_server.protocol.Entity.GameRoleData element : getGameRoleDataList()) {
        output.writeMessage(2, element);
      }
      if (hasId()) {
        output.writeString(3, getId());
      }
      if (hasMoguai()) {
        output.writeBool(4, getMoguai());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      for (com.randioo.doudizhu_server.protocol.Entity.GameRoleData element : getGameRoleDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getId());
      }
      if (hasMoguai()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, getMoguai());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.gameRoleData_ != java.util.Collections.EMPTY_LIST) {
          result.gameRoleData_ =
            java.util.Collections.unmodifiableList(result.gameRoleData_);
        }
        com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse other) {
        if (other == com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.gameRoleData_.isEmpty()) {
          if (result.gameRoleData_.isEmpty()) {
            result.gameRoleData_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.GameRoleData>();
          }
          result.gameRoleData_.addAll(other.gameRoleData_);
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMoguai()) {
          setMoguai(other.getMoguai());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder subBuilder = com.randioo.doudizhu_server.protocol.Entity.GameRoleData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGameRoleData(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setId(input.readString());
              break;
            }
            case 32: {
              setMoguai(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // repeated .com.randioo.doudizhu_server.protocol.GameRoleData gameRoleData = 2;
      public java.util.List<com.randioo.doudizhu_server.protocol.Entity.GameRoleData> getGameRoleDataList() {
        return java.util.Collections.unmodifiableList(result.gameRoleData_);
      }
      public int getGameRoleDataCount() {
        return result.getGameRoleDataCount();
      }
      public com.randioo.doudizhu_server.protocol.Entity.GameRoleData getGameRoleData(int index) {
        return result.getGameRoleData(index);
      }
      public Builder setGameRoleData(int index, com.randioo.doudizhu_server.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.gameRoleData_.set(index, value);
        return this;
      }
      public Builder setGameRoleData(int index, com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder builderForValue) {
        result.gameRoleData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.GameRoleData>();
        }
        result.gameRoleData_.add(value);
        return this;
      }
      public Builder addGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder builderForValue) {
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.GameRoleData>();
        }
        result.gameRoleData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllGameRoleData(
          java.lang.Iterable<? extends com.randioo.doudizhu_server.protocol.Entity.GameRoleData> values) {
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.GameRoleData>();
        }
        super.addAll(values, result.gameRoleData_);
        return this;
      }
      public Builder clearGameRoleData() {
        result.gameRoleData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string id = 3;
      public boolean hasId() {
        return result.hasId();
      }
      public java.lang.String getId() {
        return result.getId();
      }
      public Builder setId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = getDefaultInstance().getId();
        return this;
      }
      
      // optional bool moguai = 4;
      public boolean hasMoguai() {
        return result.hasMoguai();
      }
      public boolean getMoguai() {
        return result.getMoguai();
      }
      public Builder setMoguai(boolean value) {
        result.hasMoguai = true;
        result.moguai_ = value;
        return this;
      }
      public Builder clearMoguai() {
        result.hasMoguai = false;
        result.moguai_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.MatchJoinGameResponse)
    }
    
    static {
      defaultInstance = new MatchJoinGameResponse(true);
      com.randioo.doudizhu_server.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.MatchJoinGameResponse)
  }
  
  public static final class SCMatchJoinGame extends
      com.google.protobuf.GeneratedMessage {
    // Use SCMatchJoinGame.newBuilder() to construct.
    private SCMatchJoinGame() {
      initFields();
    }
    private SCMatchJoinGame(boolean noInit) {}
    
    private static final SCMatchJoinGame defaultInstance;
    public static SCMatchJoinGame getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCMatchJoinGame getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_SCMatchJoinGame_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Match.internal_static_com_randioo_doudizhu_server_protocol_SCMatchJoinGame_fieldAccessorTable;
    }
    
    // optional .com.randioo.doudizhu_server.protocol.GameRoleData gameRoleData = 1;
    public static final int GAMEROLEDATA_FIELD_NUMBER = 1;
    private boolean hasGameRoleData;
    private com.randioo.doudizhu_server.protocol.Entity.GameRoleData gameRoleData_;
    public boolean hasGameRoleData() { return hasGameRoleData; }
    public com.randioo.doudizhu_server.protocol.Entity.GameRoleData getGameRoleData() { return gameRoleData_; }
    
    private void initFields() {
      gameRoleData_ = com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGameRoleData()) {
        output.writeMessage(1, getGameRoleData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameRoleData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGameRoleData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame other) {
        if (other == com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame.getDefaultInstance()) return this;
        if (other.hasGameRoleData()) {
          mergeGameRoleData(other.getGameRoleData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder subBuilder = com.randioo.doudizhu_server.protocol.Entity.GameRoleData.newBuilder();
              if (hasGameRoleData()) {
                subBuilder.mergeFrom(getGameRoleData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGameRoleData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.doudizhu_server.protocol.GameRoleData gameRoleData = 1;
      public boolean hasGameRoleData() {
        return result.hasGameRoleData();
      }
      public com.randioo.doudizhu_server.protocol.Entity.GameRoleData getGameRoleData() {
        return result.getGameRoleData();
      }
      public Builder setGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameRoleData = true;
        result.gameRoleData_ = value;
        return this;
      }
      public Builder setGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData.Builder builderForValue) {
        result.hasGameRoleData = true;
        result.gameRoleData_ = builderForValue.build();
        return this;
      }
      public Builder mergeGameRoleData(com.randioo.doudizhu_server.protocol.Entity.GameRoleData value) {
        if (result.hasGameRoleData() &&
            result.gameRoleData_ != com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance()) {
          result.gameRoleData_ =
            com.randioo.doudizhu_server.protocol.Entity.GameRoleData.newBuilder(result.gameRoleData_).mergeFrom(value).buildPartial();
        } else {
          result.gameRoleData_ = value;
        }
        result.hasGameRoleData = true;
        return this;
      }
      public Builder clearGameRoleData() {
        result.hasGameRoleData = false;
        result.gameRoleData_ = com.randioo.doudizhu_server.protocol.Entity.GameRoleData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.SCMatchJoinGame)
    }
    
    static {
      defaultInstance = new SCMatchJoinGame(true);
      com.randioo.doudizhu_server.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.SCMatchJoinGame)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_MatchAIRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_MatchAIRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_SCMatchJoinGame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_SCMatchJoinGame_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Match.proto\022$com.randioo.doudizhu_serv" +
      "er.protocol\032\014Entity.proto\"^\n\026MatchCreate" +
      "GameRequest\022D\n\ngameConfig\030\001 \001(\01320.com.ra" +
      "ndioo.doudizhu_server.protocol.GameConfi" +
      "g\"\020\n\016MatchAIRequest\"\225\001\n\027MatchCreateGameR" +
      "esponse\022\024\n\terrorCode\030\001 \001(\005:\0011\022\n\n\002id\030\002 \001(" +
      "\t\022\016\n\006moguai\030\003 \001(\010\022H\n\014gameRoleData\030\004 \001(\0132" +
      "2.com.randioo.doudizhu_server.protocol.G" +
      "ameRoleData\"*\n\024MatchJoinGameRequest\022\022\n\nl" +
      "ockString\030\001 \001(\t\"\223\001\n\025MatchJoinGameRespons",
      "e\022\024\n\terrorCode\030\001 \001(\005:\0011\022H\n\014gameRoleData\030" +
      "\002 \003(\01322.com.randioo.doudizhu_server.prot" +
      "ocol.GameRoleData\022\n\n\002id\030\003 \001(\t\022\016\n\006moguai\030" +
      "\004 \001(\010\"[\n\017SCMatchJoinGame\022H\n\014gameRoleData" +
      "\030\001 \001(\01322.com.randioo.doudizhu_server.pro" +
      "tocol.GameRoleData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameRequest_descriptor,
              new java.lang.String[] { "GameConfig", },
              com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.class,
              com.randioo.doudizhu_server.protocol.Match.MatchCreateGameRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_MatchAIRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_doudizhu_server_protocol_MatchAIRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_MatchAIRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.doudizhu_server.protocol.Match.MatchAIRequest.class,
              com.randioo.doudizhu_server.protocol.Match.MatchAIRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_MatchCreateGameResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "Id", "Moguai", "GameRoleData", },
              com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse.class,
              com.randioo.doudizhu_server.protocol.Match.MatchCreateGameResponse.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameRequest_descriptor,
              new java.lang.String[] { "LockString", },
              com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.class,
              com.randioo.doudizhu_server.protocol.Match.MatchJoinGameRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameResponse_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_MatchJoinGameResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "GameRoleData", "Id", "Moguai", },
              com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse.class,
              com.randioo.doudizhu_server.protocol.Match.MatchJoinGameResponse.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_SCMatchJoinGame_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_doudizhu_server_protocol_SCMatchJoinGame_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_SCMatchJoinGame_descriptor,
              new java.lang.String[] { "GameRoleData", },
              com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame.class,
              com.randioo.doudizhu_server.protocol.Match.SCMatchJoinGame.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.doudizhu_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
