// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.randioo.doudizhu_server.protocol;

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest() {
      initFields();
    }
    private LoginRequest(boolean noInit) {}
    
    private static final LoginRequest defaultInstance;
    public static LoginRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_LoginRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_LoginRequest_fieldAccessorTable;
    }
    
    // optional string userName = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private boolean hasUserName;
    private java.lang.String userName_ = "";
    public boolean hasUserName() { return hasUserName; }
    public java.lang.String getUserName() { return userName_; }
    
    // optional string PWD = 2;
    public static final int PWD_FIELD_NUMBER = 2;
    private boolean hasPWD;
    private java.lang.String pWD_ = "";
    public boolean hasPWD() { return hasPWD; }
    public java.lang.String getPWD() { return pWD_; }
    
    // optional string headImgUrl = 3;
    public static final int HEADIMGURL_FIELD_NUMBER = 3;
    private boolean hasHeadImgUrl;
    private java.lang.String headImgUrl_ = "";
    public boolean hasHeadImgUrl() { return hasHeadImgUrl; }
    public java.lang.String getHeadImgUrl() { return headImgUrl_; }
    
    // optional int32 sex = 4 [default = 0];
    public static final int SEX_FIELD_NUMBER = 4;
    private boolean hasSex;
    private int sex_ = 0;
    public boolean hasSex() { return hasSex; }
    public int getSex() { return sex_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasUserName()) {
        output.writeString(1, getUserName());
      }
      if (hasPWD()) {
        output.writeString(2, getPWD());
      }
      if (hasHeadImgUrl()) {
        output.writeString(3, getHeadImgUrl());
      }
      if (hasSex()) {
        output.writeInt32(4, getSex());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasUserName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUserName());
      }
      if (hasPWD()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPWD());
      }
      if (hasHeadImgUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getHeadImgUrl());
      }
      if (hasSex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getSex());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Request.LoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Request.LoginRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Request.LoginRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Request.LoginRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Request.LoginRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Request.LoginRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Request.LoginRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.LoginRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Request.LoginRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Request.LoginRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Request.LoginRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.LoginRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Request.LoginRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Request.LoginRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Request.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Request.LoginRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Request.LoginRequest.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          setUserName(other.getUserName());
        }
        if (other.hasPWD()) {
          setPWD(other.getPWD());
        }
        if (other.hasHeadImgUrl()) {
          setHeadImgUrl(other.getHeadImgUrl());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setUserName(input.readString());
              break;
            }
            case 18: {
              setPWD(input.readString());
              break;
            }
            case 26: {
              setHeadImgUrl(input.readString());
              break;
            }
            case 32: {
              setSex(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string userName = 1;
      public boolean hasUserName() {
        return result.hasUserName();
      }
      public java.lang.String getUserName() {
        return result.getUserName();
      }
      public Builder setUserName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUserName = true;
        result.userName_ = value;
        return this;
      }
      public Builder clearUserName() {
        result.hasUserName = false;
        result.userName_ = getDefaultInstance().getUserName();
        return this;
      }
      
      // optional string PWD = 2;
      public boolean hasPWD() {
        return result.hasPWD();
      }
      public java.lang.String getPWD() {
        return result.getPWD();
      }
      public Builder setPWD(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPWD = true;
        result.pWD_ = value;
        return this;
      }
      public Builder clearPWD() {
        result.hasPWD = false;
        result.pWD_ = getDefaultInstance().getPWD();
        return this;
      }
      
      // optional string headImgUrl = 3;
      public boolean hasHeadImgUrl() {
        return result.hasHeadImgUrl();
      }
      public java.lang.String getHeadImgUrl() {
        return result.getHeadImgUrl();
      }
      public Builder setHeadImgUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHeadImgUrl = true;
        result.headImgUrl_ = value;
        return this;
      }
      public Builder clearHeadImgUrl() {
        result.hasHeadImgUrl = false;
        result.headImgUrl_ = getDefaultInstance().getHeadImgUrl();
        return this;
      }
      
      // optional int32 sex = 4 [default = 0];
      public boolean hasSex() {
        return result.hasSex();
      }
      public int getSex() {
        return result.getSex();
      }
      public Builder setSex(int value) {
        result.hasSex = true;
        result.sex_ = value;
        return this;
      }
      public Builder clearSex() {
        result.hasSex = false;
        result.sex_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.LoginRequest)
    }
    
    static {
      defaultInstance = new LoginRequest(true);
      com.randioo.doudizhu_server.protocol.Request.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.LoginRequest)
  }
  
  public static final class GetBattleRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use GetBattleRequest.newBuilder() to construct.
    private GetBattleRequest() {
      initFields();
    }
    private GetBattleRequest(boolean noInit) {}
    
    private static final GetBattleRequest defaultInstance;
    public static GetBattleRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public GetBattleRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_GetBattleRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_GetBattleRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.GetBattleRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Request.GetBattleRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Request.GetBattleRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Request.GetBattleRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Request.GetBattleRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Request.GetBattleRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Request.GetBattleRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Request.GetBattleRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.GetBattleRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Request.GetBattleRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Request.GetBattleRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Request.GetBattleRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.GetBattleRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Request.GetBattleRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Request.GetBattleRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Request.GetBattleRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Request.GetBattleRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Request.GetBattleRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.GetBattleRequest)
    }
    
    static {
      defaultInstance = new GetBattleRequest(true);
      com.randioo.doudizhu_server.protocol.Request.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.GetBattleRequest)
  }
  
  public static final class PlayerRejoinRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use PlayerRejoinRequest.newBuilder() to construct.
    private PlayerRejoinRequest() {
      initFields();
    }
    private PlayerRejoinRequest(boolean noInit) {}
    
    private static final PlayerRejoinRequest defaultInstance;
    public static PlayerRejoinRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayerRejoinRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_PlayerRejoinRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_PlayerRejoinRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.PlayerRejoinRequest)
    }
    
    static {
      defaultInstance = new PlayerRejoinRequest(true);
      com.randioo.doudizhu_server.protocol.Request.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.PlayerRejoinRequest)
  }
  
  public static final class NewGameRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use NewGameRequest.newBuilder() to construct.
    private NewGameRequest() {
      initFields();
    }
    private NewGameRequest(boolean noInit) {}
    
    private static final NewGameRequest defaultInstance;
    public static NewGameRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewGameRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_fieldAccessorTable;
    }
    
    public static final class GameConfig extends
        com.google.protobuf.GeneratedMessage {
      // Use GameConfig.newBuilder() to construct.
      private GameConfig() {
        initFields();
      }
      private GameConfig(boolean noInit) {}
      
      private static final GameConfig defaultInstance;
      public static GameConfig getDefaultInstance() {
        return defaultInstance;
      }
      
      public GameConfig getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_GameConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_GameConfig_fieldAccessorTable;
      }
      
      // optional int32 round = 1;
      public static final int ROUND_FIELD_NUMBER = 1;
      private boolean hasRound;
      private int round_ = 0;
      public boolean hasRound() { return hasRound; }
      public int getRound() { return round_; }
      
      // optional bool bySelfy = 2;
      public static final int BYSELFY_FIELD_NUMBER = 2;
      private boolean hasBySelfy;
      private boolean bySelfy_ = false;
      public boolean hasBySelfy() { return hasBySelfy; }
      public boolean getBySelfy() { return bySelfy_; }
      
      // optional bool laizi = 3;
      public static final int LAIZI_FIELD_NUMBER = 3;
      private boolean hasLaizi;
      private boolean laizi_ = false;
      public boolean hasLaizi() { return hasLaizi; }
      public boolean getLaizi() { return laizi_; }
      
      // optional bool useDouble = 4;
      public static final int USEDOUBLE_FIELD_NUMBER = 4;
      private boolean hasUseDouble;
      private boolean useDouble_ = false;
      public boolean hasUseDouble() { return hasUseDouble; }
      public boolean getUseDouble() { return useDouble_; }
      
      // optional int32 targetRound = 5;
      public static final int TARGETROUND_FIELD_NUMBER = 5;
      private boolean hasTargetRound;
      private int targetRound_ = 0;
      public boolean hasTargetRound() { return hasTargetRound; }
      public int getTargetRound() { return targetRound_; }
      
      // optional int32 gameType = 6;
      public static final int GAMETYPE_FIELD_NUMBER = 6;
      private boolean hasGameType;
      private int gameType_ = 0;
      public boolean hasGameType() { return hasGameType; }
      public int getGameType() { return gameType_; }
      
      // optional bool lezi = 7;
      public static final int LEZI_FIELD_NUMBER = 7;
      private boolean hasLezi;
      private boolean lezi_ = false;
      public boolean hasLezi() { return hasLezi; }
      public boolean getLezi() { return lezi_; }
      
      // optional bool huangfan = 8;
      public static final int HUANGFAN_FIELD_NUMBER = 8;
      private boolean hasHuangfan;
      private boolean huangfan_ = false;
      public boolean hasHuangfan() { return hasHuangfan; }
      public boolean getHuangfan() { return huangfan_; }
      
      // optional int32 di = 9;
      public static final int DI_FIELD_NUMBER = 9;
      private boolean hasDi;
      private int di_ = 0;
      public boolean hasDi() { return hasDi; }
      public int getDi() { return di_; }
      
      // optional bool fly = 10;
      public static final int FLY_FIELD_NUMBER = 10;
      private boolean hasFly;
      private boolean fly_ = false;
      public boolean hasFly() { return hasFly; }
      public boolean getFly() { return fly_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasRound()) {
          output.writeInt32(1, getRound());
        }
        if (hasBySelfy()) {
          output.writeBool(2, getBySelfy());
        }
        if (hasLaizi()) {
          output.writeBool(3, getLaizi());
        }
        if (hasUseDouble()) {
          output.writeBool(4, getUseDouble());
        }
        if (hasTargetRound()) {
          output.writeInt32(5, getTargetRound());
        }
        if (hasGameType()) {
          output.writeInt32(6, getGameType());
        }
        if (hasLezi()) {
          output.writeBool(7, getLezi());
        }
        if (hasHuangfan()) {
          output.writeBool(8, getHuangfan());
        }
        if (hasDi()) {
          output.writeInt32(9, getDi());
        }
        if (hasFly()) {
          output.writeBool(10, getFly());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasRound()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getRound());
        }
        if (hasBySelfy()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, getBySelfy());
        }
        if (hasLaizi()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, getLaizi());
        }
        if (hasUseDouble()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(4, getUseDouble());
        }
        if (hasTargetRound()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, getTargetRound());
        }
        if (hasGameType()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, getGameType());
        }
        if (hasLezi()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(7, getLezi());
        }
        if (hasHuangfan()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(8, getHuangfan());
        }
        if (hasDi()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(9, getDi());
        }
        if (hasFly()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(10, getFly());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig result;
        
        // Construct using com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig();
          return builder;
        }
        
        protected com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.getDescriptor();
        }
        
        public com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig getDefaultInstanceForType() {
          return com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig) {
            return mergeFrom((com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig other) {
          if (other == com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.getDefaultInstance()) return this;
          if (other.hasRound()) {
            setRound(other.getRound());
          }
          if (other.hasBySelfy()) {
            setBySelfy(other.getBySelfy());
          }
          if (other.hasLaizi()) {
            setLaizi(other.getLaizi());
          }
          if (other.hasUseDouble()) {
            setUseDouble(other.getUseDouble());
          }
          if (other.hasTargetRound()) {
            setTargetRound(other.getTargetRound());
          }
          if (other.hasGameType()) {
            setGameType(other.getGameType());
          }
          if (other.hasLezi()) {
            setLezi(other.getLezi());
          }
          if (other.hasHuangfan()) {
            setHuangfan(other.getHuangfan());
          }
          if (other.hasDi()) {
            setDi(other.getDi());
          }
          if (other.hasFly()) {
            setFly(other.getFly());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setRound(input.readInt32());
                break;
              }
              case 16: {
                setBySelfy(input.readBool());
                break;
              }
              case 24: {
                setLaizi(input.readBool());
                break;
              }
              case 32: {
                setUseDouble(input.readBool());
                break;
              }
              case 40: {
                setTargetRound(input.readInt32());
                break;
              }
              case 48: {
                setGameType(input.readInt32());
                break;
              }
              case 56: {
                setLezi(input.readBool());
                break;
              }
              case 64: {
                setHuangfan(input.readBool());
                break;
              }
              case 72: {
                setDi(input.readInt32());
                break;
              }
              case 80: {
                setFly(input.readBool());
                break;
              }
            }
          }
        }
        
        
        // optional int32 round = 1;
        public boolean hasRound() {
          return result.hasRound();
        }
        public int getRound() {
          return result.getRound();
        }
        public Builder setRound(int value) {
          result.hasRound = true;
          result.round_ = value;
          return this;
        }
        public Builder clearRound() {
          result.hasRound = false;
          result.round_ = 0;
          return this;
        }
        
        // optional bool bySelfy = 2;
        public boolean hasBySelfy() {
          return result.hasBySelfy();
        }
        public boolean getBySelfy() {
          return result.getBySelfy();
        }
        public Builder setBySelfy(boolean value) {
          result.hasBySelfy = true;
          result.bySelfy_ = value;
          return this;
        }
        public Builder clearBySelfy() {
          result.hasBySelfy = false;
          result.bySelfy_ = false;
          return this;
        }
        
        // optional bool laizi = 3;
        public boolean hasLaizi() {
          return result.hasLaizi();
        }
        public boolean getLaizi() {
          return result.getLaizi();
        }
        public Builder setLaizi(boolean value) {
          result.hasLaizi = true;
          result.laizi_ = value;
          return this;
        }
        public Builder clearLaizi() {
          result.hasLaizi = false;
          result.laizi_ = false;
          return this;
        }
        
        // optional bool useDouble = 4;
        public boolean hasUseDouble() {
          return result.hasUseDouble();
        }
        public boolean getUseDouble() {
          return result.getUseDouble();
        }
        public Builder setUseDouble(boolean value) {
          result.hasUseDouble = true;
          result.useDouble_ = value;
          return this;
        }
        public Builder clearUseDouble() {
          result.hasUseDouble = false;
          result.useDouble_ = false;
          return this;
        }
        
        // optional int32 targetRound = 5;
        public boolean hasTargetRound() {
          return result.hasTargetRound();
        }
        public int getTargetRound() {
          return result.getTargetRound();
        }
        public Builder setTargetRound(int value) {
          result.hasTargetRound = true;
          result.targetRound_ = value;
          return this;
        }
        public Builder clearTargetRound() {
          result.hasTargetRound = false;
          result.targetRound_ = 0;
          return this;
        }
        
        // optional int32 gameType = 6;
        public boolean hasGameType() {
          return result.hasGameType();
        }
        public int getGameType() {
          return result.getGameType();
        }
        public Builder setGameType(int value) {
          result.hasGameType = true;
          result.gameType_ = value;
          return this;
        }
        public Builder clearGameType() {
          result.hasGameType = false;
          result.gameType_ = 0;
          return this;
        }
        
        // optional bool lezi = 7;
        public boolean hasLezi() {
          return result.hasLezi();
        }
        public boolean getLezi() {
          return result.getLezi();
        }
        public Builder setLezi(boolean value) {
          result.hasLezi = true;
          result.lezi_ = value;
          return this;
        }
        public Builder clearLezi() {
          result.hasLezi = false;
          result.lezi_ = false;
          return this;
        }
        
        // optional bool huangfan = 8;
        public boolean hasHuangfan() {
          return result.hasHuangfan();
        }
        public boolean getHuangfan() {
          return result.getHuangfan();
        }
        public Builder setHuangfan(boolean value) {
          result.hasHuangfan = true;
          result.huangfan_ = value;
          return this;
        }
        public Builder clearHuangfan() {
          result.hasHuangfan = false;
          result.huangfan_ = false;
          return this;
        }
        
        // optional int32 di = 9;
        public boolean hasDi() {
          return result.hasDi();
        }
        public int getDi() {
          return result.getDi();
        }
        public Builder setDi(int value) {
          result.hasDi = true;
          result.di_ = value;
          return this;
        }
        public Builder clearDi() {
          result.hasDi = false;
          result.di_ = 0;
          return this;
        }
        
        // optional bool fly = 10;
        public boolean hasFly() {
          return result.hasFly();
        }
        public boolean getFly() {
          return result.getFly();
        }
        public Builder setFly(boolean value) {
          result.hasFly = true;
          result.fly_ = value;
          return this;
        }
        public Builder clearFly() {
          result.hasFly = false;
          result.fly_ = false;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.NewGameRequest.GameConfig)
      }
      
      static {
        defaultInstance = new GameConfig(true);
        com.randioo.doudizhu_server.protocol.Request.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.NewGameRequest.GameConfig)
    }
    
    // optional .com.randioo.doudizhu_server.protocol.NewGameRequest.GameConfig gameconfig = 1;
    public static final int GAMECONFIG_FIELD_NUMBER = 1;
    private boolean hasGameconfig;
    private com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig gameconfig_;
    public boolean hasGameconfig() { return hasGameconfig; }
    public com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig getGameconfig() { return gameconfig_; }
    
    private void initFields() {
      gameconfig_ = com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGameconfig()) {
        output.writeMessage(1, getGameconfig());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameconfig()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGameconfig());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.NewGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Request.NewGameRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Request.NewGameRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Request.NewGameRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Request.NewGameRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Request.NewGameRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Request.NewGameRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Request.NewGameRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.NewGameRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Request.NewGameRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Request.NewGameRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Request.NewGameRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.NewGameRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Request.NewGameRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Request.NewGameRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Request.NewGameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Request.NewGameRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Request.NewGameRequest.getDefaultInstance()) return this;
        if (other.hasGameconfig()) {
          mergeGameconfig(other.getGameconfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.Builder subBuilder = com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.newBuilder();
              if (hasGameconfig()) {
                subBuilder.mergeFrom(getGameconfig());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGameconfig(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.doudizhu_server.protocol.NewGameRequest.GameConfig gameconfig = 1;
      public boolean hasGameconfig() {
        return result.hasGameconfig();
      }
      public com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig getGameconfig() {
        return result.getGameconfig();
      }
      public Builder setGameconfig(com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameconfig = true;
        result.gameconfig_ = value;
        return this;
      }
      public Builder setGameconfig(com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.Builder builderForValue) {
        result.hasGameconfig = true;
        result.gameconfig_ = builderForValue.build();
        return this;
      }
      public Builder mergeGameconfig(com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig value) {
        if (result.hasGameconfig() &&
            result.gameconfig_ != com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.getDefaultInstance()) {
          result.gameconfig_ =
            com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.newBuilder(result.gameconfig_).mergeFrom(value).buildPartial();
        } else {
          result.gameconfig_ = value;
        }
        result.hasGameconfig = true;
        return this;
      }
      public Builder clearGameconfig() {
        result.hasGameconfig = false;
        result.gameconfig_ = com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.NewGameRequest)
    }
    
    static {
      defaultInstance = new NewGameRequest(true);
      com.randioo.doudizhu_server.protocol.Request.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.NewGameRequest)
  }
  
  public static final class JoinGameRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use JoinGameRequest.newBuilder() to construct.
    private JoinGameRequest() {
      initFields();
    }
    private JoinGameRequest(boolean noInit) {}
    
    private static final JoinGameRequest defaultInstance;
    public static JoinGameRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public JoinGameRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_JoinGameRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_JoinGameRequest_fieldAccessorTable;
    }
    
    // optional int32 gameid = 1;
    public static final int GAMEID_FIELD_NUMBER = 1;
    private boolean hasGameid;
    private int gameid_ = 0;
    public boolean hasGameid() { return hasGameid; }
    public int getGameid() { return gameid_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGameid()) {
        output.writeInt32(1, getGameid());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getGameid());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.JoinGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Request.JoinGameRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Request.JoinGameRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Request.JoinGameRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Request.JoinGameRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Request.JoinGameRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Request.JoinGameRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Request.JoinGameRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.JoinGameRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Request.JoinGameRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Request.JoinGameRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Request.JoinGameRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.JoinGameRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Request.JoinGameRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Request.JoinGameRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Request.JoinGameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Request.JoinGameRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Request.JoinGameRequest.getDefaultInstance()) return this;
        if (other.hasGameid()) {
          setGameid(other.getGameid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setGameid(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 gameid = 1;
      public boolean hasGameid() {
        return result.hasGameid();
      }
      public int getGameid() {
        return result.getGameid();
      }
      public Builder setGameid(int value) {
        result.hasGameid = true;
        result.gameid_ = value;
        return this;
      }
      public Builder clearGameid() {
        result.hasGameid = false;
        result.gameid_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.JoinGameRequest)
    }
    
    static {
      defaultInstance = new JoinGameRequest(true);
      com.randioo.doudizhu_server.protocol.Request.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.JoinGameRequest)
  }
  
  public static final class TalkRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use TalkRequest.newBuilder() to construct.
    private TalkRequest() {
      initFields();
    }
    private TalkRequest(boolean noInit) {}
    
    private static final TalkRequest defaultInstance;
    public static TalkRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public TalkRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_TalkRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Request.internal_static_com_randioo_doudizhu_server_protocol_TalkRequest_fieldAccessorTable;
    }
    
    // optional string msg = 1;
    public static final int MSG_FIELD_NUMBER = 1;
    private boolean hasMsg;
    private java.lang.String msg_ = "";
    public boolean hasMsg() { return hasMsg; }
    public java.lang.String getMsg() { return msg_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMsg()) {
        output.writeString(1, getMsg());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMsg()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMsg());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Request.TalkRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Request.TalkRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Request.TalkRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Request.TalkRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Request.TalkRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Request.TalkRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Request.TalkRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Request.TalkRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.TalkRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Request.TalkRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Request.TalkRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Request.TalkRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Request.TalkRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Request.TalkRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Request.TalkRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Request.TalkRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Request.TalkRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Request.TalkRequest.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setMsg(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string msg = 1;
      public boolean hasMsg() {
        return result.hasMsg();
      }
      public java.lang.String getMsg() {
        return result.getMsg();
      }
      public Builder setMsg(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMsg = true;
        result.msg_ = value;
        return this;
      }
      public Builder clearMsg() {
        result.hasMsg = false;
        result.msg_ = getDefaultInstance().getMsg();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.TalkRequest)
    }
    
    static {
      defaultInstance = new TalkRequest(true);
      com.randioo.doudizhu_server.protocol.Request.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.TalkRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_LoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_LoginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_GetBattleRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_GetBattleRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_PlayerRejoinRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_PlayerRejoinRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_GameConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_GameConfig_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_JoinGameRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_JoinGameRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_TalkRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_TalkRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022$com.randioo.doudizhu_se" +
      "rver.protocol\"Q\n\014LoginRequest\022\020\n\010userNam" +
      "e\030\001 \001(\t\022\013\n\003PWD\030\002 \001(\t\022\022\n\nheadImgUrl\030\003 \001(\t" +
      "\022\016\n\003sex\030\004 \001(\005:\0010\"\022\n\020GetBattleRequest\"\025\n\023" +
      "PlayerRejoinRequest\"\226\002\n\016NewGameRequest\022S" +
      "\n\ngameconfig\030\001 \001(\0132?.com.randioo.doudizh" +
      "u_server.protocol.NewGameRequest.GameCon" +
      "fig\032\256\001\n\nGameConfig\022\r\n\005round\030\001 \001(\005\022\017\n\007byS" +
      "elfy\030\002 \001(\010\022\r\n\005laizi\030\003 \001(\010\022\021\n\tuseDouble\030\004" +
      " \001(\010\022\023\n\013targetRound\030\005 \001(\005\022\020\n\010gameType\030\006 ",
      "\001(\005\022\014\n\004lezi\030\007 \001(\010\022\020\n\010huangfan\030\010 \001(\010\022\n\n\002d" +
      "i\030\t \001(\005\022\013\n\003fly\030\n \001(\010\"!\n\017JoinGameRequest\022" +
      "\016\n\006gameid\030\001 \001(\005\"\032\n\013TalkRequest\022\013\n\003msg\030\001 " +
      "\001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_doudizhu_server_protocol_LoginRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_doudizhu_server_protocol_LoginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_LoginRequest_descriptor,
              new java.lang.String[] { "UserName", "PWD", "HeadImgUrl", "Sex", },
              com.randioo.doudizhu_server.protocol.Request.LoginRequest.class,
              com.randioo.doudizhu_server.protocol.Request.LoginRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_GetBattleRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_doudizhu_server_protocol_GetBattleRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_GetBattleRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.doudizhu_server.protocol.Request.GetBattleRequest.class,
              com.randioo.doudizhu_server.protocol.Request.GetBattleRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_PlayerRejoinRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_doudizhu_server_protocol_PlayerRejoinRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_PlayerRejoinRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest.class,
              com.randioo.doudizhu_server.protocol.Request.PlayerRejoinRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_descriptor,
              new java.lang.String[] { "Gameconfig", },
              com.randioo.doudizhu_server.protocol.Request.NewGameRequest.class,
              com.randioo.doudizhu_server.protocol.Request.NewGameRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_GameConfig_descriptor =
            internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_descriptor.getNestedTypes().get(0);
          internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_GameConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_NewGameRequest_GameConfig_descriptor,
              new java.lang.String[] { "Round", "BySelfy", "Laizi", "UseDouble", "TargetRound", "GameType", "Lezi", "Huangfan", "Di", "Fly", },
              com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.class,
              com.randioo.doudizhu_server.protocol.Request.NewGameRequest.GameConfig.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_JoinGameRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_doudizhu_server_protocol_JoinGameRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_JoinGameRequest_descriptor,
              new java.lang.String[] { "Gameid", },
              com.randioo.doudizhu_server.protocol.Request.JoinGameRequest.class,
              com.randioo.doudizhu_server.protocol.Request.JoinGameRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_TalkRequest_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_doudizhu_server_protocol_TalkRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_TalkRequest_descriptor,
              new java.lang.String[] { "Msg", },
              com.randioo.doudizhu_server.protocol.Request.TalkRequest.class,
              com.randioo.doudizhu_server.protocol.Request.TalkRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
