// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Video.proto

package com.randioo.doudizhu_server.protocol;

public final class Video {
  private Video() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class VideoGetRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use VideoGetRequest.newBuilder() to construct.
    private VideoGetRequest() {
      initFields();
    }
    private VideoGetRequest(boolean noInit) {}
    
    private static final VideoGetRequest defaultInstance;
    public static VideoGetRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public VideoGetRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Video.VideoGetRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Video.VideoGetRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Video.VideoGetRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Video.VideoGetRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Video.VideoGetRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Video.VideoGetRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Video.VideoGetRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Video.VideoGetRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Video.VideoGetRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Video.VideoGetRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Video.VideoGetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Video.VideoGetRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Video.VideoGetRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.VideoGetRequest)
    }
    
    static {
      defaultInstance = new VideoGetRequest(true);
      com.randioo.doudizhu_server.protocol.Video.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.VideoGetRequest)
  }
  
  public static final class VideoGetResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use VideoGetResponse.newBuilder() to construct.
    private VideoGetResponse() {
      initFields();
    }
    private VideoGetResponse(boolean noInit) {}
    
    private static final VideoGetResponse defaultInstance;
    public static VideoGetResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public VideoGetResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // repeated .com.randioo.doudizhu_server.protocol.videoWithId videoMsg = 2;
    public static final int VIDEOMSG_FIELD_NUMBER = 2;
    private java.util.List<com.randioo.doudizhu_server.protocol.Entity.videoWithId> videoMsg_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.doudizhu_server.protocol.Entity.videoWithId> getVideoMsgList() {
      return videoMsg_;
    }
    public int getVideoMsgCount() { return videoMsg_.size(); }
    public com.randioo.doudizhu_server.protocol.Entity.videoWithId getVideoMsg(int index) {
      return videoMsg_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      for (com.randioo.doudizhu_server.protocol.Entity.videoWithId element : getVideoMsgList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      for (com.randioo.doudizhu_server.protocol.Entity.videoWithId element : getVideoMsgList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Video.VideoGetResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Video.VideoGetResponse result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Video.VideoGetResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Video.VideoGetResponse();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Video.VideoGetResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Video.VideoGetResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetResponse.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetResponse getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Video.VideoGetResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Video.VideoGetResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.videoMsg_ != java.util.Collections.EMPTY_LIST) {
          result.videoMsg_ =
            java.util.Collections.unmodifiableList(result.videoMsg_);
        }
        com.randioo.doudizhu_server.protocol.Video.VideoGetResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Video.VideoGetResponse) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Video.VideoGetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Video.VideoGetResponse other) {
        if (other == com.randioo.doudizhu_server.protocol.Video.VideoGetResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.videoMsg_.isEmpty()) {
          if (result.videoMsg_.isEmpty()) {
            result.videoMsg_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.videoWithId>();
          }
          result.videoMsg_.addAll(other.videoMsg_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.doudizhu_server.protocol.Entity.videoWithId.Builder subBuilder = com.randioo.doudizhu_server.protocol.Entity.videoWithId.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addVideoMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // repeated .com.randioo.doudizhu_server.protocol.videoWithId videoMsg = 2;
      public java.util.List<com.randioo.doudizhu_server.protocol.Entity.videoWithId> getVideoMsgList() {
        return java.util.Collections.unmodifiableList(result.videoMsg_);
      }
      public int getVideoMsgCount() {
        return result.getVideoMsgCount();
      }
      public com.randioo.doudizhu_server.protocol.Entity.videoWithId getVideoMsg(int index) {
        return result.getVideoMsg(index);
      }
      public Builder setVideoMsg(int index, com.randioo.doudizhu_server.protocol.Entity.videoWithId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.videoMsg_.set(index, value);
        return this;
      }
      public Builder setVideoMsg(int index, com.randioo.doudizhu_server.protocol.Entity.videoWithId.Builder builderForValue) {
        result.videoMsg_.set(index, builderForValue.build());
        return this;
      }
      public Builder addVideoMsg(com.randioo.doudizhu_server.protocol.Entity.videoWithId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.videoMsg_.isEmpty()) {
          result.videoMsg_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.videoWithId>();
        }
        result.videoMsg_.add(value);
        return this;
      }
      public Builder addVideoMsg(com.randioo.doudizhu_server.protocol.Entity.videoWithId.Builder builderForValue) {
        if (result.videoMsg_.isEmpty()) {
          result.videoMsg_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.videoWithId>();
        }
        result.videoMsg_.add(builderForValue.build());
        return this;
      }
      public Builder addAllVideoMsg(
          java.lang.Iterable<? extends com.randioo.doudizhu_server.protocol.Entity.videoWithId> values) {
        if (result.videoMsg_.isEmpty()) {
          result.videoMsg_ = new java.util.ArrayList<com.randioo.doudizhu_server.protocol.Entity.videoWithId>();
        }
        super.addAll(values, result.videoMsg_);
        return this;
      }
      public Builder clearVideoMsg() {
        result.videoMsg_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.VideoGetResponse)
    }
    
    static {
      defaultInstance = new VideoGetResponse(true);
      com.randioo.doudizhu_server.protocol.Video.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.VideoGetResponse)
  }
  
  public static final class VideoGetByIdRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use VideoGetByIdRequest.newBuilder() to construct.
    private VideoGetByIdRequest() {
      initFields();
    }
    private VideoGetByIdRequest(boolean noInit) {}
    
    private static final VideoGetByIdRequest defaultInstance;
    public static VideoGetByIdRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public VideoGetByIdRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdRequest_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.VideoGetByIdRequest)
    }
    
    static {
      defaultInstance = new VideoGetByIdRequest(true);
      com.randioo.doudizhu_server.protocol.Video.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.VideoGetByIdRequest)
  }
  
  public static final class VideoGetByIdResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use VideoGetByIdResponse.newBuilder() to construct.
    private VideoGetByIdResponse() {
      initFields();
    }
    private VideoGetByIdResponse(boolean noInit) {}
    
    private static final VideoGetByIdResponse defaultInstance;
    public static VideoGetByIdResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public VideoGetByIdResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional .com.randioo.doudizhu_server.protocol.videoWithId videoMsg = 2;
    public static final int VIDEOMSG_FIELD_NUMBER = 2;
    private boolean hasVideoMsg;
    private com.randioo.doudizhu_server.protocol.Entity.videoWithId videoMsg_;
    public boolean hasVideoMsg() { return hasVideoMsg; }
    public com.randioo.doudizhu_server.protocol.Entity.videoWithId getVideoMsg() { return videoMsg_; }
    
    private void initFields() {
      videoMsg_ = com.randioo.doudizhu_server.protocol.Entity.videoWithId.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasVideoMsg()) {
        output.writeMessage(2, getVideoMsg());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasVideoMsg()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getVideoMsg());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse other) {
        if (other == com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasVideoMsg()) {
          mergeVideoMsg(other.getVideoMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.doudizhu_server.protocol.Entity.videoWithId.Builder subBuilder = com.randioo.doudizhu_server.protocol.Entity.videoWithId.newBuilder();
              if (hasVideoMsg()) {
                subBuilder.mergeFrom(getVideoMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVideoMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.videoWithId videoMsg = 2;
      public boolean hasVideoMsg() {
        return result.hasVideoMsg();
      }
      public com.randioo.doudizhu_server.protocol.Entity.videoWithId getVideoMsg() {
        return result.getVideoMsg();
      }
      public Builder setVideoMsg(com.randioo.doudizhu_server.protocol.Entity.videoWithId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasVideoMsg = true;
        result.videoMsg_ = value;
        return this;
      }
      public Builder setVideoMsg(com.randioo.doudizhu_server.protocol.Entity.videoWithId.Builder builderForValue) {
        result.hasVideoMsg = true;
        result.videoMsg_ = builderForValue.build();
        return this;
      }
      public Builder mergeVideoMsg(com.randioo.doudizhu_server.protocol.Entity.videoWithId value) {
        if (result.hasVideoMsg() &&
            result.videoMsg_ != com.randioo.doudizhu_server.protocol.Entity.videoWithId.getDefaultInstance()) {
          result.videoMsg_ =
            com.randioo.doudizhu_server.protocol.Entity.videoWithId.newBuilder(result.videoMsg_).mergeFrom(value).buildPartial();
        } else {
          result.videoMsg_ = value;
        }
        result.hasVideoMsg = true;
        return this;
      }
      public Builder clearVideoMsg() {
        result.hasVideoMsg = false;
        result.videoMsg_ = com.randioo.doudizhu_server.protocol.Entity.videoWithId.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.VideoGetByIdResponse)
    }
    
    static {
      defaultInstance = new VideoGetByIdResponse(true);
      com.randioo.doudizhu_server.protocol.Video.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.VideoGetByIdResponse)
  }
  
  public static final class VideoGetByRoundRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use VideoGetByRoundRequest.newBuilder() to construct.
    private VideoGetByRoundRequest() {
      initFields();
    }
    private VideoGetByRoundRequest(boolean noInit) {}
    
    private static final VideoGetByRoundRequest defaultInstance;
    public static VideoGetByRoundRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public VideoGetByRoundRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundRequest_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional int32 round = 2;
    public static final int ROUND_FIELD_NUMBER = 2;
    private boolean hasRound;
    private int round_ = 0;
    public boolean hasRound() { return hasRound; }
    public int getRound() { return round_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasRound()) {
        output.writeInt32(2, getRound());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasRound()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getRound());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest other) {
        if (other == com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRound()) {
          setRound(other.getRound());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 16: {
              setRound(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional int32 round = 2;
      public boolean hasRound() {
        return result.hasRound();
      }
      public int getRound() {
        return result.getRound();
      }
      public Builder setRound(int value) {
        result.hasRound = true;
        result.round_ = value;
        return this;
      }
      public Builder clearRound() {
        result.hasRound = false;
        result.round_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.VideoGetByRoundRequest)
    }
    
    static {
      defaultInstance = new VideoGetByRoundRequest(true);
      com.randioo.doudizhu_server.protocol.Video.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.VideoGetByRoundRequest)
  }
  
  public static final class VideoGetByRoundResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use VideoGetByRoundResponse.newBuilder() to construct.
    private VideoGetByRoundResponse() {
      initFields();
    }
    private VideoGetByRoundResponse(boolean noInit) {}
    
    private static final VideoGetByRoundResponse defaultInstance;
    public static VideoGetByRoundResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public VideoGetByRoundResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.doudizhu_server.protocol.Video.internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional .com.randioo.doudizhu_server.protocol.video videoMsg = 2;
    public static final int VIDEOMSG_FIELD_NUMBER = 2;
    private boolean hasVideoMsg;
    private com.randioo.doudizhu_server.protocol.Entity.video videoMsg_;
    public boolean hasVideoMsg() { return hasVideoMsg; }
    public com.randioo.doudizhu_server.protocol.Entity.video getVideoMsg() { return videoMsg_; }
    
    private void initFields() {
      videoMsg_ = com.randioo.doudizhu_server.protocol.Entity.video.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasVideoMsg()) {
        output.writeMessage(2, getVideoMsg());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasVideoMsg()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getVideoMsg());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse result;
      
      // Construct using com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse();
        return builder;
      }
      
      protected com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse.getDescriptor();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse getDefaultInstanceForType() {
        return com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse) {
          return mergeFrom((com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse other) {
        if (other == com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasVideoMsg()) {
          mergeVideoMsg(other.getVideoMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.doudizhu_server.protocol.Entity.video.Builder subBuilder = com.randioo.doudizhu_server.protocol.Entity.video.newBuilder();
              if (hasVideoMsg()) {
                subBuilder.mergeFrom(getVideoMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVideoMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional .com.randioo.doudizhu_server.protocol.video videoMsg = 2;
      public boolean hasVideoMsg() {
        return result.hasVideoMsg();
      }
      public com.randioo.doudizhu_server.protocol.Entity.video getVideoMsg() {
        return result.getVideoMsg();
      }
      public Builder setVideoMsg(com.randioo.doudizhu_server.protocol.Entity.video value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasVideoMsg = true;
        result.videoMsg_ = value;
        return this;
      }
      public Builder setVideoMsg(com.randioo.doudizhu_server.protocol.Entity.video.Builder builderForValue) {
        result.hasVideoMsg = true;
        result.videoMsg_ = builderForValue.build();
        return this;
      }
      public Builder mergeVideoMsg(com.randioo.doudizhu_server.protocol.Entity.video value) {
        if (result.hasVideoMsg() &&
            result.videoMsg_ != com.randioo.doudizhu_server.protocol.Entity.video.getDefaultInstance()) {
          result.videoMsg_ =
            com.randioo.doudizhu_server.protocol.Entity.video.newBuilder(result.videoMsg_).mergeFrom(value).buildPartial();
        } else {
          result.videoMsg_ = value;
        }
        result.hasVideoMsg = true;
        return this;
      }
      public Builder clearVideoMsg() {
        result.hasVideoMsg = false;
        result.videoMsg_ = com.randioo.doudizhu_server.protocol.Entity.video.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.doudizhu_server.protocol.VideoGetByRoundResponse)
    }
    
    static {
      defaultInstance = new VideoGetByRoundResponse(true);
      com.randioo.doudizhu_server.protocol.Video.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.doudizhu_server.protocol.VideoGetByRoundResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_VideoGetRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_VideoGetRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_VideoGetResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_VideoGetResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Video.proto\022$com.randioo.doudizhu_serv" +
      "er.protocol\032\014Entity.proto\"\021\n\017VideoGetReq" +
      "uest\"m\n\020VideoGetResponse\022\024\n\terrorCode\030\001 " +
      "\001(\005:\0011\022C\n\010videoMsg\030\002 \003(\01321.com.randioo.d" +
      "oudizhu_server.protocol.videoWithId\"!\n\023V" +
      "ideoGetByIdRequest\022\n\n\002id\030\001 \001(\005\"q\n\024VideoG" +
      "etByIdResponse\022\024\n\terrorCode\030\001 \001(\005:\0011\022C\n\010" +
      "videoMsg\030\002 \001(\01321.com.randioo.doudizhu_se" +
      "rver.protocol.videoWithId\"3\n\026VideoGetByR" +
      "oundRequest\022\n\n\002id\030\001 \001(\005\022\r\n\005round\030\002 \001(\005\"n",
      "\n\027VideoGetByRoundResponse\022\024\n\terrorCode\030\001" +
      " \001(\005:\0011\022=\n\010videoMsg\030\002 \001(\0132+.com.randioo." +
      "doudizhu_server.protocol.video"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_VideoGetRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.doudizhu_server.protocol.Video.VideoGetRequest.class,
              com.randioo.doudizhu_server.protocol.Video.VideoGetRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_VideoGetResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "VideoMsg", },
              com.randioo.doudizhu_server.protocol.Video.VideoGetResponse.class,
              com.randioo.doudizhu_server.protocol.Video.VideoGetResponse.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdRequest_descriptor,
              new java.lang.String[] { "Id", },
              com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest.class,
              com.randioo.doudizhu_server.protocol.Video.VideoGetByIdRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_VideoGetByIdResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "VideoMsg", },
              com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse.class,
              com.randioo.doudizhu_server.protocol.Video.VideoGetByIdResponse.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundRequest_descriptor,
              new java.lang.String[] { "Id", "Round", },
              com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest.class,
              com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundRequest.Builder.class);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_doudizhu_server_protocol_VideoGetByRoundResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "VideoMsg", },
              com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse.class,
              com.randioo.doudizhu_server.protocol.Video.VideoGetByRoundResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.doudizhu_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
